### ISSUE TITLE
Sierra - Handoff and Airdrop not working

### ISSUE THREAD

**Issue by NBChick** [dokterdok/Continuity-Activation-Tool#355]
Have you tried [these steps](https://github.com/dokterdok/Continuity-Activation-Tool/wiki#cant-open-the-tool)?
Umm

Is there already an open topic for this issue?
Sort of? 

Please include the following information.
- OS Version: Sierra 10.12
- Mac model: 2011 27" iMac 
- Dongle or replaced card?: 802.11ac BCM94360CD BT4.0 Wifi Card
- Used dongle/card: ASUS USB-BT400 Bluetooth 4.0 USB Adapter

Your Issue:
Was on Yosemite, had replaced the wifi card with the 802.11ac BCM94360CD BT4.0 Wifi Card and added in the Asus USB-BT400 Bluetooth 4.0 USB Adapter. Ran CAT and lived happily. 
Till Sierra. 

Steps done to try to fix the issue:
I did the upgrade and seemingly Hand-off wormed it's way through the upgrade. I was surprised to see after updating that "Allow handoff between this Mac and your iCloud devices" was still present in the system preferences and I hadn't re-run the CAT tool yet. But the features do not work. I tried uninstalling CAT, the setting stays there. Tried reinstalling CAT but it's already active. I tried to uninstall a few times. It refuses to leave. Forced CAT to reinstall via terminal, no luck. Signed out of icloud and back in and it works sort of, not stable. As soon as the machine restarts, handoff stops working all together again. Unplugged and plugged the BT dongle in. Double checked the wifi networks. Even reinstalled Sierra (Over the current install) Tried disabling and re-enabling icloud drive. I have searched google, I've been following the issues here hoping a solution would pop up but nothing yet :( I have an iPhone on 8.4, an iPad on 9.0.2 and a Macbook Air on Sierra 10.12 <- they all talk to eachother fine. My iMac won't join their clique though. 
Any ideas? My brain is scattered trying to figure this out

**Comment by NBChick** [comment]
Upon restarting, Im now getting this window pop-up
"Error: Kext developer mode not set
Kext developer mode is not set!
This might result in unusable WiFi/Bluetooth
Do you want to open Continuity Activation to to fix this?"
[Dismiss]  [Open Continuity Activation Tool]

Fixed this issue, DIsabled SIP again (must have been turned on again when I reinstalled Sierra) and forced CAT installation again. 

Right now it's working sporadically. Definitely not as stable as it was on Yosemite though

**Comment by gajahduduk** [comment]
Basically I'm in the same situation. MacPro 2009 with Wifi/BT4 card from OSXWifi. (details attached).  Handoff supported, option to enabled handoff in Sys Prefs General on.   Handoff worked in El Capitan, does not in Sierra (in my case at all). "cloudpaird: system supports Continuity"

CAT 2.3 reported my card was not whitelisted.  would not correct because OSX already supported continuity.  turned off SIP, ran CAT with -f option from terminal. Then it reported that my card was whitelisted, etc., all ok.

Rebooted with SIP on, toggled all relevant settings (toggled iCloud drive but not iCloud totally, since I've done that several times and it's a real PIA to set things up again.) But Handoff still doesn't work.

I saw in another thread that I should look at SystemParameters.plist. (also attached) I did, and didn't see a "true" for any of the ContinuitySupport keys.  Don't know what that means at all.  Is that related to the whitelist?

[CAT_Info.zip](https://github.com/dokterdok/Continuity-Activation-Tool/files/629179/CAT_Info.zip)

**Comment by Konstrukteur** [comment]
I have the OSWifi card too in my Mac Pro 2010. The card has 802.11AC and BT 4.2. 

AirDrop works.
Continuity and Handoff not.

I do not use CAT. On OSWifi it was stated that the card would not need any driver, etc.

What happened is that I only get 802.11 link speeds. I tried connecting to iPad Air 2 and MacBook Pro 2016, but get only 802.11N speeds.

Maybe Sierra blocks everything?

**Comment by jpvalensi** [comment]
Same issues as KONSTRUKTEUR.  Anyone have a clue what's up?  Same situation with Sierra 10.12.2

**Comment by FatMixG** [comment]
MacBook Pro (17-inch, Mid 2009) running OS X El Capitan 10.11.6 (15G22010), 3.06 GHz Intel Core 2 Duo. Blue tooth not working since I messed with the Continuity Activation Tool to try and get the handoff working. Big mistake. Luckily I have my old hard drive and can reboot to it, but it still doesn't let me do the handoff.  Now I get: 

Kext developer mode is not set!
This might result in unusable WiFi/Bluetooth
Do you want to open Continuity Activation to to fix this?

Help!!!
